name: Run renovate on local repository

on:
  schedule:
    # Run every hour
    - cron: '33 * * * *'

  workflow_dispatch:
    inputs:
      dryRun:
        description: 'Dry run mode'
        required: false
        default: ''
        type: choice
        options:
          - ''
          - 'extract'
          - 'lookup'
          - 'full'
      logLevel:
        description: 'Log level'
        required: false
        default: 'info'
        type: choice
        options:
          - 'debug'
          - 'info'
          - 'warning'
          - 'critical'

  push:
    branches:
      - master
    paths:
      # Re-run when config changes
      - '.forgejo/workflows/renovate.yaml'
      - 'renovate.json5'
      - 'renovate.json'

jobs:
  renovate:
    name: Call Renovate
    uses: kjh/actions/.forgejo/workflows/renovate.yaml@main
    secrets: inherit
    with:
      dryRun: ${{ inputs.dryRun }}
      logLevel: ${{ inputs.logLevel }}
